 const resList = [
   {
     info: {
       id: "125850",
       name: "La Pino'z Pizza",
       cloudinaryImageId: "y8xhvzf61t0zatbefstk",
       locality: "Evershine Tower",
       areaName: "Vaishali Nagar",
       costForTwo: "₹400 for two",
       cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
       avgRating: 4.1,
       parentId: "4961",
       avgRatingString: "4.1",
       totalRatingsString: "5K+",
       deliveryTime: 19,
       sla: {
         deliveryTime: 19,
         lastMileTravel: 1.6,
         serviceability: "SERVICEABLE",
         slaString: "19 mins",
         lastMileTravelString: "1.6 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 02:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "50% OFF",
         subHeader: "UPTO ₹100",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/la-pinoz-pizza-evershine-tower-vaishali-nagar-jaipur-125850",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "90186",
       name: "Burger King",
       cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹350 for two",
       cuisines: ["Burgers", "American"],
       avgRating: 4.3,
       parentId: "166",
       avgRatingString: "4.3",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 23,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "23 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 04:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "60% OFF",
         subHeader: "UPTO ₹120",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/burger-king-amrapali-marg-vaishali-nagar-jaipur-90186",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "45972",
       name: "Burger Farm",
       cloudinaryImageId: "670695b88d5cf2fcb2e3c135ceb2f71f",
       locality: "Vaishali Nagar",
       areaName: "Vaishali Nagar",
       costForTwo: "₹200 for two",
       cuisines: [
         "American",
         "Continental",
         "Italian-American",
         "Snacks",
         "Combo",
         "Grill",
         "Beverages",
         "Desserts",
         "Indian",
         "Barbecue",
       ],
       avgRating: 4.4,
       parentId: "4660",
       avgRatingString: "4.4",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 25,
         lastMileTravel: 3,
         serviceability: "SERVICEABLE",
         slaString: "25 mins",
         lastMileTravelString: "3.0 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 02:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "30% OFF",
         subHeader: "UPTO ₹75",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/burger-farm-vaishali-nagar-jaipur-45972",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "45810",
       name: "Falahaar & Kota Kachori",
       cloudinaryImageId: "3198495edc9215c39d001593cb9d6b10",
       locality: "Queens Road",
       areaName: "Vaishali Nagar",
       costForTwo: "₹200 for two",
       cuisines: ["North Indian", "Snacks", "Indian"],
       avgRating: 4.4,
       veg: true,
       parentId: "7019",
       avgRatingString: "4.4",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 25,
         lastMileTravel: 3.9,
         serviceability: "SERVICEABLE",
         slaString: "25 mins",
         lastMileTravelString: "3.9 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 22:00:00",
         opened: true,
       },
       badges: {
         imageBadges: [
           {
             imageId: "v1695133679/badges/Pure_Veg111.png",
             description: "pureveg",
           },
         ],
       },
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {
             badgeObject: [
               {
                 attributes: {
                   description: "pureveg",
                   imageId: "v1695133679/badges/Pure_Veg111.png",
                 },
               },
             ],
           },
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "₹100 OFF",
         subHeader: "ABOVE ₹499",
         discountTag: "FLAT DEAL",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/falahaar-and-kota-kachori-queens-road-vaishali-nagar-jaipur-45810",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "45604",
       name: "Domino's Pizza",
       cloudinaryImageId: "s3fd3put3dbwlecpgb35",
       locality: "Vaishali Nagar",
       areaName: "Vaishali Nagar",
       costForTwo: "₹400 for two",
       cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
       avgRating: 4.2,
       parentId: "2456",
       avgRatingString: "4.2",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 25,
         serviceability: "SERVICEABLE",
         slaString: "25 mins",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 00:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "30% OFF",
         subHeader: "UPTO ₹75",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/dominos-pizza-vaishali-nagar-jaipur-45604",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "47597",
       name: "Pizza Hut",
       cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
       locality: "Evershine Tower",
       areaName: "Vaishali Nagar",
       costForTwo: "₹350 for two",
       cuisines: ["Fast Food", "Pizzas"],
       avgRating: 3.9,
       parentId: "721",
       avgRatingString: "3.9",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 27,
         lastMileTravel: 1.6,
         serviceability: "SERVICEABLE",
         slaString: "27 mins",
         lastMileTravelString: "1.6 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 04:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "60% OFF",
         subHeader: "UPTO ₹120",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/pizza-hut-evershine-tower-vaishali-nagar-jaipur-47597",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "368395",
       name: "Bikkgane Biryani",
       cloudinaryImageId: "56646c3f698b3c5ae53639c49a4725af",
       locality: "Rani Sati Nagar",
       areaName: "Vaishali Nagar",
       costForTwo: "₹350 for two",
       cuisines: [
         "Biryani",
         "Hyderabadi",
         "Andhra",
         "South Indian",
         "North Indian",
         "Mughlai",
         "Kebabs",
       ],
       avgRating: 4.3,
       parentId: "5070",
       avgRatingString: "4.3",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 22,
         lastMileTravel: 1,
         serviceability: "SERVICEABLE",
         slaString: "22 mins",
         lastMileTravelString: "1.0 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 00:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "₹175 OFF",
         subHeader: "ABOVE ₹449",
         discountTag: "FLAT DEAL",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/bikkgane-biryani-rani-sati-nagar-vaishali-nagar-jaipur-368395",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "199969",
       name: "Sweet Truth - Cake and Desserts",
       cloudinaryImageId: "2bff7ef1c40b8a1d356fcf9d487324f9",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹450 for two",
       cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
       avgRating: 4.3,
       parentId: "4444",
       avgRatingString: "4.3",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 19,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "19 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "60% OFF",
         subHeader: "UPTO ₹110",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/sweet-truth-cake-and-desserts-amrapali-marg-vaishali-nagar-jaipur-199969",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "45640",
       name: "Baskin Robbins - Ice Cream Desserts",
       cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
       locality: "Shivraj Niketan Colony",
       areaName: "Vaishali Nagar",
       costForTwo: "₹300 for two",
       cuisines: ["Ice Cream", "Desserts"],
       avgRating: 4.5,
       veg: true,
       parentId: "5588",
       avgRatingString: "4.5",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 19,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "19 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 02:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "30% OFF",
         subHeader: "UPTO ₹75",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-shivraj-niketan-colony-vaishali-nagar-jaipur-45640",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "199973",
       name: "The Good Bowl",
       cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹400 for two",
       cuisines: [
         "Biryani",
         "North Indian",
         "Pastas",
         "Punjabi",
         "Desserts",
         "Beverages",
       ],
       avgRating: 4.4,
       parentId: "7918",
       avgRatingString: "4.4",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 21,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "21 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "50% OFF",
         subHeader: "UPTO ₹100",
         discountTag: "POCKET HERO",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/the-good-bowl-amrapali-marg-vaishali-nagar-jaipur-199973",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "222081",
       name: "Bombay Misthan Bhandar",
       cloudinaryImageId: "127d6d2a1a4f3e995fba2c5dd93b574f",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹300 for two",
       cuisines: [
         "North Indian",
         "Thalis",
         "Rajasthani",
         "Snacks",
         "Sweets",
         "Indian",
       ],
       avgRating: 4.4,
       veg: true,
       parentId: "387367",
       avgRatingString: "4.4",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 18,
         lastMileTravel: 1.5,
         serviceability: "SERVICEABLE",
         slaString: "18 mins",
         lastMileTravelString: "1.5 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "60% OFF",
         subHeader: "UPTO ₹120",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/bombay-misthan-bhandar-amrapali-marg-vaishali-nagar-jaipur-222081",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "345822",
       name: "Biryani Blues",
       cloudinaryImageId: "cdc2y3ntatwb01xs61j8",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹400 for two",
       cuisines: ["Biryani", "Kebabs", "Lucknowi", "Hyderabadi", "Mughlai"],
       avgRating: 4.4,
       parentId: "13813",
       avgRatingString: "4.4",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 24,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "24 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 04:00:00",
         opened: true,
       },
       badges: {
         textExtendedBadges: [
           {
             iconId: "guiltfree/GF_Logo_android_3x",
             shortDescription: "options available",
             fontColor: "#7E808C",
           },
         ],
       },
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {
             badgeObject: [
               {
                 attributes: {
                   description: "",
                   fontColor: "#7E808C",
                   iconId: "guiltfree/GF_Logo_android_3x",
                   shortDescription: "options available",
                 },
               },
             ],
           },
         },
       },
       aggregatedDiscountInfoV3: {
         header: "50% OFF",
         subHeader: "UPTO ₹100",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/biryani-blues-amrapali-marg-vaishali-nagar-jaipur-345822",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "199961",
       name: "Behrouz Biryani",
       cloudinaryImageId: "89fccaa76f2f760e2742b9e53d32bb69",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹500 for two",
       cuisines: [
         "Biryani",
         "North Indian",
         "Kebabs",
         "Mughlai",
         "Lucknowi",
         "Hyderabadi",
         "Desserts",
         "Beverages",
       ],
       avgRating: 4.4,
       parentId: "1803",
       avgRatingString: "4.4",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 24,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "24 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "60% OFF",
         subHeader: "UPTO ₹110",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/behrouz-biryani-amrapali-marg-vaishali-nagar-jaipur-199961",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "199960",
       name: "Faasos - Wraps, Rolls & Shawarma",
       cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹500 for two",
       cuisines: [
         "Kebabs",
         "Fast Food",
         "Snacks",
         "North Indian",
         "American",
         "Healthy Food",
         "Desserts",
         "Beverages",
       ],
       avgRating: 4.4,
       parentId: "21809",
       avgRatingString: "4.4",
       totalRatingsString: "5K+",
       sla: {
         deliveryTime: 26,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "26 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "50% OFF",
         subHeader: "UPTO ₹100",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/faasos-wraps-rolls-and-shawarma-amrapali-marg-vaishali-nagar-jaipur-199960",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "199964",
       name: "Oven Story Pizza - Standout Toppings",
       cloudinaryImageId: "ab979bffbd658e74de650a15ca0092a3",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹400 for two",
       cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
       avgRating: 4,
       parentId: "3534",
       avgRatingString: "4.0",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 28,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "23-33 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "60% OFF",
         subHeader: "UPTO ₹120",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/oven-story-pizza-standout-toppings-amrapali-marg-vaishali-nagar-jaipur-199964",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "199976",
       name: "LunchBox - Meals and Thalis",
       cloudinaryImageId: "l8nk3hwqji6sjqzzmz9w",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹300 for two",
       cuisines: [
         "Biryani",
         "North Indian",
         "Punjabi",
         "Healthy Food",
         "Desserts",
         "Beverages",
       ],
       avgRating: 4.2,
       parentId: "4925",
       avgRatingString: "4.2",
       totalRatingsString: "1K+",
       sla: {
         deliveryTime: 24,
         lastMileTravel: 1.4,
         serviceability: "SERVICEABLE",
         slaString: "24 mins",
         lastMileTravelString: "1.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "ITEMS",
         subHeader: "AT ₹159",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/lunchbox-meals-and-thalis-amrapali-marg-vaishali-nagar-jaipur-199976",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "567272",
       name: "EatFit - Desi Meals, Burgers & More",
       cloudinaryImageId: "6126c9b45de2cb222405c1af8a321e74",
       locality: "Chitrakoot Scheme",
       areaName: "Vaishali Nagar",
       costForTwo: "₹270 for two",
       cuisines: [
         "Chinese",
         "Healthy Food",
         "Tandoor",
         "Pizzas",
         "North Indian",
         "Thalis",
         "Biryani",
       ],
       avgRating: 4.1,
       parentId: "76139",
       avgRatingString: "4.1",
       totalRatingsString: "500+",
       sla: {
         deliveryTime: 21,
         lastMileTravel: 2.4,
         serviceability: "SERVICEABLE",
         slaString: "21 mins",
         lastMileTravelString: "2.4 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:59:00",
         opened: true,
       },
       badges: {
         textExtendedBadges: [
           {
             iconId: "guiltfree/GF_Logo_android_3x",
             shortDescription: "brand",
             fontColor: "#7E808C",
           },
         ],
       },
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {
             badgeObject: [
               {
                 attributes: {
                   description: "",
                   fontColor: "#7E808C",
                   iconId: "guiltfree/GF_Logo_android_3x",
                   shortDescription: "brand",
                 },
               },
             ],
           },
         },
       },
       aggregatedDiscountInfoV3: {
         header: "ITEMS",
         subHeader: "AT ₹159",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/eatfit-desi-meals-burgers-and-more-chitrakoot-scheme-vaishali-nagar-jaipur-567272",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "59226",
       name: "The Belgian Waffle Co.",
       cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
       locality: "Amrapali Marg",
       areaName: "Vaishali Nagar",
       costForTwo: "₹200 for two",
       cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
       avgRating: 4.4,
       veg: true,
       parentId: "2233",
       avgRatingString: "4.4",
       totalRatingsString: "5K+",
       sla: {
         deliveryTime: 30,
         lastMileTravel: 1.5,
         serviceability: "SERVICEABLE",
         slaString: "30 mins",
         lastMileTravelString: "1.5 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 02:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "20% OFF",
         subHeader: "UPTO ₹50",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/the-belgian-waffle-co-amrapali-marg-vaishali-nagar-jaipur-59226",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "47395",
       name: "Subway",
       cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
       locality: "Bopal",
       areaName: "Elements Mall",
       costForTwo: "₹200 for two",
       cuisines: [
         "Fast Food",
         "Healthy Food",
         "Salads",
         "Desserts",
         "Beverages",
         "Snacks",
         "Continental",
         "Italian",
         "Italian-American",
         "American",
       ],
       avgRating: 3.9,
       parentId: "2",
       avgRatingString: "3.9",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 30,
         lastMileTravel: 3.6,
         serviceability: "SERVICEABLE",
         slaString: "30 mins",
         lastMileTravelString: "3.6 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-24 01:00:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "40% OFF",
         subHeader: "UPTO ₹80",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/subway-bopal-elements-mall-jaipur-47395",
       type: "WEBLINK",
     },
   },
   {
     info: {
       id: "50386",
       name: "Natural Ice Cream",
       cloudinaryImageId: "i3kgdqqrmcqqvbska88g",
       locality: "Vaishali Nagar",
       areaName: "Vaishali Nagar",
       costForTwo: "₹150 for two",
       cuisines: ["Ice Cream", "Desserts"],
       avgRating: 4.8,
       parentId: "2093",
       avgRatingString: "4.8",
       totalRatingsString: "10K+",
       sla: {
         deliveryTime: 18,
         lastMileTravel: 2.1,
         serviceability: "SERVICEABLE",
         slaString: "18 mins",
         lastMileTravelString: "2.1 km",
         iconType: "ICON_TYPE_EMPTY",
       },
       availability: {
         nextCloseTime: "2023-12-23 23:30:00",
         opened: true,
       },
       badges: {},
       isOpen: true,
       type: "F",
       badgesV2: {
         entityBadges: {
           imageBased: {},
           textBased: {},
           textExtendedBadges: {},
         },
       },
       aggregatedDiscountInfoV3: {
         header: "20% OFF",
         discountTag: "FLAT DEAL",
       },
       loyaltyDiscoverPresentationInfo: {
         logoCtx: {
           logo: "Swiggy%20One%20Lite/One_lite_vertical_logo.png",
         },
         freedelMessage: "FREE DELIVERY",
         badgeType: "BADGE_TYPE_ONE_LITE",
       },
       differentiatedUi: {
         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
         differentiatedUiMediaDetails: {
           mediaType: "ADS_MEDIA_ENUM_IMAGE",
           lottie: {},
           video: {},
         },
       },
       reviewsSummary: {},
       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
       restaurantOfferPresentationInfo: {},
     },
     analytics: {},
     cta: {
       link: "https://www.swiggy.com/restaurants/natural-ice-cream-vaishali-nagar-jaipur-50386",
       type: "WEBLINK",
     },
   },
 ];

export default resList;